version = 0.1

[default]
[default.global.parameters]
stack_name = "demand-letter"

[default.build.parameters]
cached = true
parallel = true

[default.local_start_api.parameters]
port           = 3000
env_vars       = "env.json"
docker_network = "demand-letter-dev"

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-east-1"
